[feat] Switching using command
Swithcing to using commmand instead of which for dependencies.

diff --git a/kubernetes/kubepatchsecrets b/kubernetes/kubepatchsecrets
--- a/kubernetes/kubepatchsecrets
+++ b/kubernetes/kubepatchsecrets
@@ -7,13 +7,13 @@ DATE="2023-12-04"
 SCRIPT_NAME=$(basename "$0")
 
 # Verify dependencies
-if [ -z $(which jq) ] ; then
+if [ -z "$(command -v jq)" ]; then
   echo "Application jq required to use this tool!"
   exit 1
 fi
-if [ -z $(which kubectl) ] ; then
-    echo "Application kubectl required to use this tool!"
-    exit 1
+if [ -z "$(command -v kubectl)" ]; then
+  echo "Application kubectl required to use this tool!"
+  exit 1
 fi
 
 verbose_print() {
diff --git a/kubernetes/kubesecrets b/kubernetes/kubesecrets
--- a/kubernetes/kubesecrets
+++ b/kubernetes/kubesecrets
@@ -8,13 +8,13 @@ DATE="2023-12-04"
 SCRIPT_NAME=$(basename "$0")
 
 # Verify dependencies
-if [ -z $(which jq) ] ; then
+if [ -z "$(command -v jq)" ]; then
   echo "Application jq required to use this tool!"
   exit 1
 fi
-if [ -z $(which kubectl) ] ; then
-    echo "Application kubectl required to use this tool!"
-    exit 1
+if [ -z "$(command -v kubectl)" ]; then
+  echo "Application kubectl required to use this tool!"
+  exit 1
 fi
 
 check_secret() {
@@ -82,16 +82,6 @@ decode_secrets() {
         fi
     done < <(kubectl -n "$namespace" get secrets "$secret_name" -o json | jq -r '.data | to_entries[] | "\(.key)\t\(.value)"')
 }
-
-# Verify dependencies
-if [ -z "$(command -v jq)" ]; then
-  echo "Application jq required to use this tool!"
-  exit 1
-fi
-if [ -z "$(command -v kubectl)" ]; then
-  echo "Application kubectl required to use this tool!"
-  exit 1
-fi
 
 # Default values
 VERBOSE=false
